### PR TITLE
fixed error with format strings

### PR DESCRIPTION
**Pull request by CDaut**
A bunch of missing format strings caused the library to not compile for me 
(CMake 3.29.2, nixos)
This PR fixes this issue by adding the format literals.

### CODE REVIEW

**Comment by NBickford-NV** [comment]
Hi @CDaut, thanks for submitting this pull request! This looks good to me; I had a go at setting up Nix on WSL on Windows 11, and can confirm these are errors there.

(We probably didn't catch these because these are only warnings on our Ubuntu Linux CI. For other maintainers, this was because NixOS's `gcc` is a wrapper script that enables various hardening flags around the `gcc` executable; see https://nixos.wiki/wiki/C. On NixOS 23.11.7042.9a9960b98418, the defaults are `-fPIC -O2 -U_FORTIFY_SOURCE -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong --param ssp-buffer-size=4 -fno-strict-overflow`)

I'll do some additional checks to make sure this covers everything, and then hopefully merge this in.

Just to double-check, since I'm running Nix for the first time -- I'm setting up my environment using `nix-shell --packages cmake git glm glslang libGL python3 shaderc shaderc.static vulkan-headers vulkan-loader vulkan-tools vulkan-validation-layers xorg.{libX11,libXcursor,libXi,libXinerama,libXrandr,libXxf86vm}` and re-running extensions_vk.py since the 23.11 stream's Vulkan headers are a bit old; does that look OK to you?

Thanks!

**Comment by CDaut** [comment]
Hi @NBickford-NV,
Yes, that looks fine. I can provide you with a nix flake that I use for developing C++ and vulkan. You can find the flake [here](https://git.cdaut.de/CDaut/bluenoise-raytracer/-/blob/master/flake.nix?ref_type=heads) and the corresponding lockfile [here](https://git.cdaut.de/CDaut/bluenoise-raytracer/-/blob/master/flake.lock?ref_type=heads) (ensures that we are running the same version).
To use the flake copy both files into the root of the repository and run ``nix develop``. This command has to be [enabled before](https://nixos.wiki/wiki/Nix_command). Using flakes ensures a consistent build environment.
If you wish to entirely reproduce my environment you can find my nix files [here](https://git.cdaut.de/CDaut/nix) although that would probably be overkill.
Thanks for looking into this issue so thoroughly!

**Comment by CDaut** [comment]
I am sorry, I appear to have done something wrong by missing to sign off the commits. It should all be correct now but i'd still ask you to double check please.

**Comment by NBickford-NV** [comment]
Hi @CDaut ! I finished looking into this, and this looks good -- I'll go ahead and merge it!

It turned out that samples that used NVML also needed some changes -- I needed to modify FindNVML.cmake to potentially fall back to the NVML stub library since Nix's `cuda` package doesn't include the full NVML library (which might be packaged with the driver instead), and fix some similar format string issues that only appeared in element_nvml.hpp and vk_mini_samples. These improvements will be included in a bulk update soon.

In case it helps anyone else, my `flake.nix` for the nvpro-samples dependencies including CUDA wound up looking like this:

```
{
  description = "Nix flake for developing nvpro-samples with CUDA";
 
  outputs = {nixpkgs, ...}: let
    system = "x86_64-linux";
    pkgs = nixpkgs.legacyPackages.${system};
  in {
    devShells.${system}.default = pkgs.mkShell {
      packages = with pkgs; [
        gcc11 # Since the `cudatoolkit` and default `gcc` packages aren't compatible as of this writing
        cmake
        git
        glm
        glslang
        libGL
        python3
        shaderc
        shaderc.static
        vulkan-headers
        vulkan-loader
        vulkan-tools
        vulkan-validation-layers
        xorg.libX11
        xorg.libXcursor
        xorg.libXi
        xorg.libXinerama
        xorg.libXrandr
        xorg.libXxf86vm
        # New additions for CUDA
        cudatoolkit
      ];
    };
  };
}
```

Running `export NIXPKGS_ALLOW_UNFREE=1` (since CUDA's not FOSS) followed by `nix develop --impure` then gets me into a development environment that can build all the samples except for ones involving DirectX, OptiX, and NVTT.

Thanks!

**Pull request merged**
